[book]
title="Strapify Documentation"
description="Documentation for the Strapify library"
authors = ["Ray Keating", "Austin Gooodman"]
language = "en"
multilingual = false
src = "src"
[output.html]
git-repository-url = "https://github.com/strapify-dev/Strapify"
git-repository-icon = "fa-github"
preferred-dark-theme = "ayu"
preferred-light-theme = "light"
additional-css = ["src/custom.css"]
[build]
build-dir = "website/docs"